# Generated by Django 3.2.12 on 2022-09-19 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20220919_0210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consume',
            new_name='selected_item',
        ),
    ]
